module.exports.boards = {
  Gossiping: [],
  WomenTalk: [],
  StupidClown: [],
  'Boy-Girl': [],
  LoL: [],
  WOW: [],
  movie: [],
  KoreaDrama: [],
  Baseball: [],
  NBA: [],
  MLB: [],
  Tech_Job: [],
  Soft_Job: [],
  PC_Shopping: [],
  Beauty: [],
  joke: [],
  Stock: [],
  MobileComm: [],
  marvel: [],
  C_Chat: [],
};

module.exports.mapBoardToCategory = {
  Gossiping: '八卦',
  WomenTalk: '女版',
  StupidClown: '笨版',
  'Boy-Girl': '兩性',
  LoL: '英雄聯盟',
  WOW: '魔獸世界',
  movie: '電影',
  KoreaDrama: '韓劇',
  Baseball: '棒球',
  NBA: 'NBA',
  MLB: '大聯盟',
  Tech_Job: '科技',
  Soft_Job: '軟體',
  PC_Shopping: '電蝦',
  Beauty: '表特',
  joke: '就可',
  Stock: '股市',
  MobileComm: '3C',
  marvel: '媽佛',
  C_Chat: '希洽',
};
